source $DZS/libs/dzs.zsh
source $DZS/libs/completion.zsh
source $DZS/libs/directories.zsh
source $DZS/libs/git.zsh
source $DZS/libs/grep.zsh
source $DZS/libs/history.zsh
source $DZS/libs/key-bindings.zsh
source $DZS/libs/termsupport.zsh
source $DZS/libs/theme-appearence.zsh
source $DZS/plugins/extract/extract.plugin.zsh
source $DZS/plugins/fzf-tab/fzf-tab.zsh
source $DZS/plugins/powerlevel10k/powerlevel10k.zsh-theme
source $DZS/plugins/sudo/sudo.plugin.zsh
source $DZS/plugins/z.lua/z.lua.plugin.zsh
source $DZS/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source $DZS/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
